import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";



export const metadata: Metadata = {
  title: "Dina Holding | SA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-hero bg-no-repeat bg-cover bg-fixed -z-10 antialiased `}>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
